### ISSUE TITLE
Latest Build of Forge for minecraft 1.14.4 breaks mod

### ISSUE THREAD

**Issue by raziel23x** [MC-U-Team/Useful-Ores#1]
like title states updating to the latest build of forge breaks mod

**Comment by HyCraftHD** [comment]
Is there a crashreport or does it not load?

**Comment by raziel23x** [comment]
![image](https://user-images.githubusercontent.com/441966/62426608-00301e00-b6b5-11e9-8c4f-e6ff0e062942.png)

**Comment by raziel23x** [comment]
here is the latest.log
https://paste.dimdev.org/uxajehocew.md

**Comment by HyCraftHD** [comment]
Okay thanks! Might be because of the implementation of IStringSerializable here: 
Because thats not needed I can just remove that.
https://github.com/MC-U-Team/Useful-Resources/blob/1.14.4/src/main/java/info/u_team/useful_resources/type/ResourceItemTypes.java#L18

**Comment by raziel23x** [comment]
from what i have noticed from the past few days with forge that they have changed much of the api and added some new stuff and this probably caused some code in places to break got to love ALPHA Build for Forge to break stuff on every commit

**Comment by HyCraftHD** [comment]
I think thats more of a obfuscation issues here, because the getName method is implemented in IStringSerializable and an other interface. The IStringSerializable will be obfuscated leaving the getName method unimplemented in that class which cause the crash. Thats totally my mistake here ^^

**Comment by HyCraftHD** [comment]
I'll update asap

**Comment by raziel23x** [comment]
the last few updates to forge also broke Building gadgets and rftools power so i was assuming this was the case here as well

**Comment by HyCraftHD** [comment]
The new builds on curseforge should fix that crash
